# Generated by Django 3.1.1 on 2020-09-08 10:02

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('order_category', models.CharField(choices=[('Buy', 'Buy'), ('Sell', 'Sell')], max_length=10)),
                ('order_time', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('order_quantity', models.IntegerField()),
                ('order_type', models.CharField(choices=[('LM', 'Limit'), ('MR', 'Market')], max_length=10)),
                ('order_price', models.IntegerField()),
                ('No_extra', models.BooleanField()),
                ('All_or_none', models.BooleanField(blank=True, null=True)),
                ('Minimum_fill', models.IntegerField(blank=True, null=True)),
                ('Disclosed_Quantity', models.IntegerField(blank=True, null=True)),
                ('order_status', models.CharField(editable=False, max_length=10)),
            ],
        ),
    ]
