# Generated by Django 3.1.1 on 2020-09-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergenerator', '0002_order_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='No_extra',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_quantity',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('LM', 'Limit'), ('MR', 'Market')], default='MR', max_length=10),
        ),
    ]
