# Generated by Django 3.1.1 on 2020-09-10 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordergenerator', '0003_auto_20200909_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='No_extra',
        ),
    ]
