# Generated by Django 3.1.1 on 2020-09-16 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergenerator', '0004_auto_20200915_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradePrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_trade_price', models.FloatField(default=100, editable=False)),
                ('last_trade_day', models.DateTimeField(default=datetime.date.today, editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='trade_price_list',
            field=models.TextField(default='', editable=False, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='trade_quant_list',
            field=models.TextField(default='', editable=False, max_length=200),
        ),
    ]
