# Generated by Django 3.1.1 on 2020-09-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordergenerator', '0005_auto_20200916_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='trade_id',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
